spring:
  #접속DB설정
  datasource:
    url: "jdbc:log4jdbc:mysql://localhost:3308/test?serverTimezone=UTC&allowPublicKeyRetrieval=true"
    username: "root"
    password: "1234"
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /resources/**
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    thymeleaf:
      cache: false

mybatis:
  # mapper 경로지정
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 9099
  servlet:
    context-path: /
  jsp:
    servlet:
      init:
        parameters:
          development: true
